### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by pedroserano** [dnschneid/pysmartblinds#1]
This is awesome, thank you so much for all your hard work on this. This is a tremendous help and the thought of getting my blinds to work with homekit is very exciting. I was wondering if you have any thoughts on creating a homebridge plugin for this?

**Comment by dnschneid** [comment]
I'm not too interested in making plugins for all the various platforms (there are a lot, and since I don't use them, it's pretty hard to test), but I'm happy to review pull requests.  Writing plugins should be trivial if you can use Python libraries.

For Homebridge, though, it looks like it uses node.js, while this library is written in Python.  It might be easiest if you just use the httpserver example and have homebridge talk to those endpoints.

**Comment by pedroserano** [comment]
That's a great suggestion. As suggested, I combined an http-based homebridge blinds plugin ([homebridge-minimal-http-blinds](https://github.com/Nicnl/homebridge-minimal-http-blinds)) seamlessly with your httpserver python example script. I just ran the httpserver.py directly using:

`python3 httpserver.py`

and used the URL format it creates for the homebridge plugin config.json.
For anyone that comes across this, since it took me a minute to find the URL format, it is:

`http://[ip address of computer running python script]:1500/[blind name as defined in BLINDS array in httpserver]/[action: up, down, stop, set, pos]/[optional for set: percentage open for blind]`

For Example, if my raspberry pi running httpserver.py is 192.168.7.107, to get the position of the living room blind named "living_room", the URL is:

`http://192.168.7.107:1500/living_room/pos`

For the set command, there's an additional percentage open, for example if setting at 50%:

`http://192.168.7.107:1500/living_room/set/50`

P.S. The httpserver example did require a tweak for me because python3 was unhappy with the variable form. I had to change line 97 in httpserver.py to:

`        message = str(BLINDS[blind]['blind'].pos())`
`        self.wfile.write(message.encode('utf-8'))`

**Comment by dnschneid** [comment]
Awesome; thanks for sharing how you got that working!

I've fixed the GET bug (whoops), and improved the documentation.  There's one further feature that wasn't obvious: `/blind_name/set/pos/secs` will transition to position `pos` over `secs` seconds.  Mainly good for automations as it keeps the noise of the blinds down by doing smaller steps.
