### ISSUE TITLE
Open should up(), Close should be blind.down()

### ISSUE THREAD

**Issue by jumpkick** [dnschneid/pysmartblinds#11]
Currently, we have this:
```
    def open_cover_tilt(self, **kwargs):
        """Tilt the cover open. We define that as tilting down."""
        self._blind.down()
```
This isn't consistent with how roll-down covers work...  which are "on" when they roll down and block light and "off" when they roll up and let light in.

It occurs to me as I just finished writing that, that in your run through setting up the blinds, you may have chosen the tilt to be reversed for "close" than I have for mine... I'm not sure how that choice during the set-up within the app effects the blinds operation, so this setting may not be the same for you.

**Comment by dnschneid** [comment]
I definitely struggled with what the correct direction for this is, but I think it's correct as it is.  I interpreted "open" as letting in light (pointing downwards), and "closed" as blocking it (pointing upwards).

I'm surprised that your roll-down covers are considered "on" when closed.  Are you sure this is the case?  From what I can tell from the code, we (and other covers) [simply report when we are considered "closed"](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/cover/__init__.py#L183) and HomeAssistant itself interprets that as off.

In both the roll-down case and our case, we are "closed" when blocking light, so I can't see how the current behavior is inconsistent.

**Comment by dnschneid** [comment]
Now, if you're finding that .close() moves the blinds into a light-emitting position, that probably means we're not handling config correctly.

**Comment by jumpkick** [comment]
I guess I should mention the "on"/"off" interpretation comes from Amazon Alexa not understanding what a cover device is and haaska mapping covers as simple on/off switch devices.  Like in a sense a blind is active when it blocks light, inactive when it allows light in....   But in English we say it's closed or open...  I dunno...   I suppose it doesn't matter. 😴

**Comment by dnschneid** [comment]
That still sounds backwards, and doesn't match the hass UI, which considers open to be on (and shows a highlighted icon).  The thought is if you want to shut off all light to a room, you turn off the lights and close the blinds.

Anyway, as far as I can tell it's the Alexa integration that's doing weird things, not HomeAssistant and not this plugin...
