### ISSUE TITLE
Firmware 2.1 Support

### ISSUE THREAD

**Issue by jtinst** [dnschneid/pysmartblinds#17]
My blinds are running MCU 2.1.  Has anyone confirmed whether or not this library will work?  search.py did not work for me, but (I think) I got my passkey using the Android Bluetooth snoop log and Wireshark.  Using that passkey and MAC, httpserver.py throws the following error when I try to GET /pos:

`----------------------------------------
Exception happened during processing of request from ('10.18.85.12', 30491)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "httpserver.py", line 97, in do_GET
    self.wfile.write(b'%d' % BLINDS[blind]['blind'].pos())
TypeError: unsupported operand type(s) for %: 'bytes' and 'int'
----------------------------------------
`

Am I just out of luck with 2.1, or am I doing something else wrong?  Happy to help try to develop 2.1 support if possible.

**Comment by jtinst** [comment]
I know very little python, but I was able to fix this error by changing line 97 to the following:
` self.wfile.write(b'%d' % bytes(BLINDS[blind]['blind'].pos()))`

With that edit, I can control my blinds.  So, I can confirm that it is possible to control blinds running firmware 2.1.

**Comment by nickverschuren** [comment]
Is this still working? ive been trying hard to get the blinds in home assistant but no luck yet. I'm having problems retrieving my key. But if it's not even working anymore, i'd love to hear about it.

**Comment by dnschneid** [comment]
Still works for me, but we never narrowed down the discrepancies in key retrieval.

Most reliable way to retrieve your key is via parsing an Android bluetooth dump via Wireshark.

**Comment by nickverschuren** [comment]
Ok, don’t know what that is, but i’m going to research it. Thank you!

Op 3 aug. 2020 om 22:56 heeft David Schneider <notifications@github.com> het volgende geschreven:

﻿

Still works for me, but we never narrowed down the discrepancies in key retrieval.

Most reliable way to retrieve your key is via parsing an Android bluetooth dump via Wireshark.

**Comment by nickverschuren** [comment]
I’m trying to find out how this works but could you possibly point me out in the right direction? I would appreciate it.

On 3 Aug 2020, at 22:56, David Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:



Still works for me, but we never narrowed down the discrepancies in key retrieval.

Most reliable way to retrieve your key is via parsing an Android bluetooth dump via Wireshark.

**Comment by nickverschuren** [comment]
I do have Wireshark btw, on a linux vm

On 3 Aug 2020, at 22:56, David Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:



Still works for me, but we never narrowed down the discrepancies in key retrieval.

Most reliable way to retrieve your key is via parsing an Android bluetooth dump via Wireshark.

**Comment by dnschneid** [comment]
The method I used is in [an old version of the readme](https://github.com/dnschneid/pysmartblinds/blob/f8d209eb491291d4c16235dd74b1d538b52c926e/README.md#android), but it may not work for you.

**Comment by nickverschuren** [comment]
Perfect. I think i got it. I can’t find the util/extractkeys.py file.

But im guessing the key is the one starting with T?

[cid:118AA6ED-9253-466A-95FD-3694093BE70C-L0-001]

Op 5 aug. 2020 om 20:53 heeft David Schneider <notifications@github.com> het volgende geschreven:

﻿

The method I used is in an old version of the readme<https://github.com/dnschneid/pysmartblinds/blob/f8d209eb491291d4c16235dd74b1d538b52c926e/README.md#android>, but it may not work for you.

**Comment by dnschneid** [comment]
It's in [the same commit](https://github.com/dnschneid/pysmartblinds/raw/f8d209eb491291d4c16235dd74b1d538b52c926e/util/extractkeys.py).

**Comment by nickverschuren** [comment]
I finally got all the Mac addresses and the keys. Had to look through them since they were all different Mac addresses. Thank you so much!

Now the last step is to add it to ha. I added this to my config file:

cover:
   - platform: mysmartblinds
     blinds:
       first_blind:
         friendly_name: Raam 1
         mac: 'f4:6d:e5:54:1b:8d'
         access_token: ’27'


I’m getting the error:

Platform error cover.mysmartblinds - Integration 'mysmartblinds' not found.

Ive had this error when trying to add ianlevasque’s to my config. And looked for a long time on finding the answer, but I don’t understand how everything works just yet. Is there a place I need to add the Mysmartblinds integration?

Hope this is my last question, sorry

**Comment by dnschneid** [comment]
The instructions in mysmartblinds.py are out-of-date.  I've updated them (although I haven't gotten the chance to test it yet), so please try it out and file a separate bug if it still doesn't work.

**Comment by nickverschuren** [comment]
Ill do that, just installed the update. I don’t know how to apply cover.patch though. And this error pops up. Ill file a bug report.


[cid:29E7177A-87B4-40D0-B9FB-353CE6B8B82D]

**Comment by nickverschuren** [comment]
Im trying to use your patch file, but im running home assistant in a docker container. I can’t seem to use to patch file on it. Do you know how?

Kind regards

> Op 8 aug. 2020 om 15:46 heeft nick verschuren <nickverschuren@hotmail.com> het volgende geschreven:
> 
> ﻿
> Ill do that, just installed the update. I don’t know how to apply cover.patch though. And this error pops up. Ill file a bug report.
> 
> 
> <Screenshot 2020-08-08 at 07.44.53.png>

**Comment by nickverschuren** [comment]
Any updates?

> Op 8 aug. 2020 om 15:46 heeft nick verschuren <nickverschuren@hotmail.com> het volgende geschreven:
> 
> ﻿
> Ill do that, just installed the update. I don’t know how to apply cover.patch though. And this error pops up. Ill file a bug report.
> 
> 
> <Screenshot 2020-08-08 at 07.44.53.png>

**Comment by nickverschuren** [comment]
I am haha, but not a lot of response, I’ve installed Raspbian GNU/Linux 10 (buster) on a ssd and then installed home assistant supervised in docker. (I used a online guide how to do it.)

Do you know where I can place it?

Would be a great help, or if you can point me in the right direction would also help. This is the last thing I’m trying to incorporate and its been taking forever.

Thanks anyways

Nick

> Op 8 aug. 2020 om 15:46 heeft nick verschuren <nickverschuren@hotmail.com> het volgende geschreven:
> 
> ﻿
> Ill do that, just installed the update. I don’t know how to apply cover.patch though. And this error pops up. Ill file a bug report.
> 
> 
> <Screenshot 2020-08-08 at 07.44.53.png>

**Comment by dnschneid** [comment]
Nick, are you running firmware v2.1 on your blinds?  If so, and you were able to control the blinds via the basic control script, then this bug can be closed.

Please re-open if that's not the case.
