### ISSUE TITLE
Update home assistant example

### ISSUE THREAD

**Issue by nickverschuren** [dnschneid/pysmartblinds#18]
Getting the following error:

Platform error cover.mysmartblinds - No module named 'custom_components.mysmartblinds.cover'
7:40:47 – Hass.io (ERROR)

(have yet to apply cover.patch to my homeAssistant install, because I don't know how yet...)

**Comment by dnschneid** [comment]
The updated instructions have a different location for the files, so please make sure you placed them in the right location.
You will also need to ensure that pysmartblinds.py is somewhere in your PYTHONPATH for your install.

**Comment by dnschneid** [comment]
Don't worry about the patch file until after you have the blinds working; it's only needed to enable slow transitions in automations.

**Comment by nickverschuren** [comment]
Ive added the correct files. But i don’t know how to add to my PYTHONPATH. i have home assistant installed in docker on the latest linux distribution. I can share files with samba and i have acces to the Ha terminal from inside home assistant. As well acces to the host terminal via ssh.

How do i add something ty PYTHONOATH install?

Kind regards

Op 18 aug. 2020 om 20:11 heeft David Schneider <notifications@github.com> het volgende geschreven:

﻿

The updated instructions have a different location for the files, so please make sure you placed them in the right location.
You will also need to ensure that pysmartblinds.py is somewhere in your PYTHONPATH for your install.

**Comment by nickverschuren** [comment]
Im still trying to add the pysmartblinds.py somewhere in my PYTHONPATH, but I don’t know what that is or where to put it.

**Comment by dnschneid** [comment]
That's specific to whatever method you used to install homeassistant; maybe ask for help on the homeassistant discord?

**Comment by nickverschuren** [comment]
I am haha, but not a lot of response, I’ve installed Raspbian GNU/Linux 10 (buster) on a ssd and then installed home assistant supervised in docker. (I used a online guide how to do it.)

Do you know where I can place it?

Would be a great help, or if you can point me in the right direction would also help. This is the last thing I’m trying to incorporate and its been taking forever.

Thanks anyways

Nick

**Comment by nickverschuren** [comment]
Ant chance you know where i can add that file to my PYTHONPATH? Im really at a loss. Tried installing pyscriot and hacs and many other thungs. But none helped me get the blinds working. If i could add it this would help me out a lot. 

Thanks again!

> Op 25 aug. 2020 om 23:08 heeft nick verschuren <nickverschuren@hotmail.com> het volgende geschreven:
> 
> ﻿I am haha, but not a lot of response, I’ve installed Raspbian GNU/Linux 10 (buster) on a ssd and then installed home assistant supervised in docker. (I used a online guide how to do it.)
> 
> Do you know where I can place it?
> 
> Would be a great help, or if you can point me in the right direction would also help. This is the last thing I’m trying to incorporate and its been taking forever.
> 
> Thanks anyways
> 
> Nick
>
