### ISSUE TITLE
hass pysmartblinds.py error

### ISSUE THREAD

**Issue by nickverschuren** [dnschneid/pysmartblinds#19]
Getting this error when adding pysmartblinds.py to Hass through pyscript.

Logboekdetails (ERROR)
Logger: custom_components.pyscript.file.pysmartblinds
Source: custom_components/pyscript/__init__.py:227 
Integration: Pyscript Python scripting (documentation, issues) 
First occurred: 15:42:45 (1 occurrences) 
Last logged: 15:42:45

Exception in </config/pyscript/pysmartblinds.py> line 34: from threading import Timer ^ ModuleNotFoundError: import from threading not allowed

**Comment by dnschneid** [comment]
Sorry, I really can't support environment issues.  If you come across a bug with the library or examples I'll look into it, but you'll need to ask elsewhere if you're having trouble configuring python correctly.
