### ISSUE TITLE
MySmartBlinds bridge?

### ISSUE THREAD

**Issue by jer78** [dnschneid/pysmartblinds#2]
Wondering if you were looking at updating this to work with the bridge instead of just Bluetooth? Also would you be able to port over to Home Assistant? It uses Python so it’s probably not too hard though I wouldn’t know where to start.

**Comment by dnschneid** [comment]
Not really.  The bridge is unnecessary if you can directly connect via bluetooth (well, except that this library currently can only handle one connection at a time).  You might also be able to control the blinds via the bridge already with HomeAssistant's support for Alexa and Assistant, but I haven't looked into that.

As for this library and HomeAssistant, there's a component in the [examples folder](https://github.com/dnschneid/pysmartblinds/blob/master/examples/mysmartblinds.py).  That's what I've been using, personally.

**Comment by jer78** [comment]
Ok thanks. I’ll take a look at the HA custom component. I’ve had issues in the past controlling Bluetooth with my older Mac Mini since it doesn’t support BLE. I may give this a try and see if it works later this week but if it’s ever possible to reverse engineer the hub since it works over WiFi and can connect to more than 1 blind, let me know. I’d love to help out in any way I can.

**Comment by dnschneid** [comment]
I don't have an inclination to do so, but I'm happy to accept pull requests if you can figure it out.  I'd be concerned that it's implemented via a secure link to MySmartBlind's servers, and you may not be able to spoof it directly.
