### ISSUE TITLE
Instructions for capturing Bluetooth HCI log outdated, Extract Keys yields no matches 

### ISSUE THREAD

**Issue by jumpkick** [dnschneid/pysmartblinds#3]
When I attempted to dump out Bluetooth HCI logs, my bug report zip didn't contain any bluetooth logs...   After referring to this answer on stackoverflow (https://stackoverflow.com/a/30352487/2288993) that suggests google is moving away from providing that file, I was able to extract the bluetooth log data with the following steps:

```
unzip bugreport.zip bugreport*.txt 
curl "https://android.googlesource.com/platform/system/bt/+/master/tools/scripts/btsnooz.py?format=TEXT" | base64 -D - > btsnooz.py
python btsnooz.py bugreport-*.txt > btsnoop_hci.log
```

When I run strings on that, I get my phone model number and a bunch of "SmartBlind_DFU", so I believe it captured something.

However, when I run extractkeys.py on the data, I get no output.   extractkeys.py does run as it complains if I don't provide the log file as arg. 

Any suggestions as to how I might be able to extract the keys?   Is the mac perhaps printed on the unit somewhere? (I haven't taken one down to look).

**Comment by jumpkick** [comment]
I have a couple of captures now, one from a 1+ 5T (Oreo) to 5 different blinds and another from a Nexus 5 (Marshmellow) to 1 of blinds (from an older version of the app), they both load up in Wireshark.  I'm not seeing any GATT 0x001b packets that are 7 bytes long.   Is there a specific filter or packet sequence that one needs to look for?

**Comment by jumpkick** [comment]
Hey @pedroserano, as the only other person besides @dnschneid (saw your closed issue) to get this code working, were you able to just use extractkeys.py or did you end up isolating the key using wireshark on the BT log or some other technique?   I'd be very grateful for any tips you could share.  Thx

**Comment by dnschneid** [comment]
Do you know what firmware version your blinds are running?  I had only one datapoint when writing everything, so I wouldn't be surprised if some of my assumptions didn't hold up in the general case.

**Comment by jumpkick** [comment]
I have 4 running at 2.0 MCU / 2.0 BLE, and 1 at 1.7 / 1.19

**Comment by dnschneid** [comment]
Whoa, that's an exciting setup.  Keep in mind that the current library can't talk to multiple blinds concurrently (although it should be OK doing it sequentially).

Would you be OK sending me your snoop logs?

**Comment by dnschneid** [comment]
Thanks; I'll look at it when I can set aside some time.

**Comment by dnschneid** [comment]
Ok, from your logs, I've learned the following:

1. MySmartBlinds BT MAC addresses are totally random.  Kinda lame, but whatever.
2. All five of your device secrets are 3 bytes, not 7.  Why?  No idea.

Open up your logs in Wireshark and apply the filter `(btatt.handle == 0x001b) && (btatt.opcode == 0x12)` to get a mapping of MACs to secrets.  I've pushed a patch to accept 3-byte secrets.  Let me know if those work, and I'll try to improve `extractkeys.py`.

**Comment by jumpkick** [comment]
Found the keys..  I also took a look at my Nexus5 dump and the key is longer however the first 3-bytes are common, so I'm not sure what to make of that... but I'll attach that packet here.

[Nexus5-MM-Older-App.log](https://github.com/dnschneid/pysmartblinds/files/2563051/Nexus5-MM-Older-App.log)

Seems the addresses these things use are Bluetooth Addresses (Random) vs Mac addresses that filter by vendor (this mentions: https://stackoverflow.com/questions/32703686/difference-between-mac-address-and-bluetooth-address)...

**Comment by dnschneid** [comment]
first three bytes, not four bytes?  Do the last three bytes match the keys found in the other log?

If there were a common first four bytes, I would have assumed it to be an account identifier, but the mismatched fourth byte is strange.

**Comment by jumpkick** [comment]
Value is: 5bxxxx in the 3-byte log from the OnePlus
Value is: 5bxxxx563481ff in the Nexus 5 log

Not sure what the direction the data is ordered, but that's how it matches in wireshark.

**Comment by dnschneid** [comment]
Nifty.  I'll try dropping the last four bytes on mine and see if it still works.

**Comment by dnschneid** [comment]
Oh wow, I dropped all but the first byte and it still works.  Can you try only sending that first byte (0x5b in your case, I think) and see if things still work?

**Comment by jumpkick** [comment]
I haven't had any luck connecting to the one blind that reports as being in range...   I might be doing it wrong though...  here's what I tried

```
cd ~/source/pysmartblinds/examples
sudo hcitool lescan # take the first address matching SmartBlind_DFU
ln -s ../pysmartblinds/pysmartblinds.py
nano httpserver.py # replace 'mac' with the value from hcitool, replace 'key' with the 3-bytes from snoop log matching that BD_ADDR
sudo python3.5 -m pip install pygatt # install pygatt
python3.5 httpserver.py &
curl "http://localhost:1500/living_room/pos"; echo #  0
curl -X POST "http://localhost:1500/living_room/down"; echo # error 504 - nothing happens
```

I wonder if it would work if you sent a random value to yours...

**Comment by jumpkick** [comment]
oh wait a second... one of my blinds closed... whoa...

**Comment by jumpkick** [comment]
Ok, I'm having some success now....  Seems to be a bit of a timing thing going on...

If I send too early I get a 504, so I need to wait a couple of seconds after the server comes up.
I then seem to have a short window I can send commands and get activity from, then I guess the BLE connection times out and we get the "pygatt.exceptions.NotificationTimeout" error.

curl -X POST "http://localhost:1500/living_room/set/120"; echo # worked
# 127.0.0.1 - - [09/Nov/2018 14:35:25] "POST /living_room/set/120 HTTP/1.1" 204 -

Now that I have it going with the 7-bytes I'll try trimming the key down to 3.

**Comment by dnschneid** [comment]
Excellent.  If the one-byte version works, I might be able to simplify the initial setup process.

**Comment by jumpkick** [comment]
3-byte works....
If I cut down to 1-byte + 2 0x0, it fails... 
If I put just 1-byte, it pysmartblind barfs:

```
Original exception was:
Traceback (most recent call last):
  File "httpserver.py", line 109, in <module>
    init_devices()
  File "httpserver.py", line 40, in init_devices
    blind['blind'] = Blind(blind['mac'], blind['key'])
  File "/home/ged/source/pysmartblinds/examples/pysmartblinds.py", line 59, in __init__
    self._key = key[:7]
TypeError: 'int' object is not subscriptable
```

What did you patch to make it take 1-byte?

**Comment by dnschneid** [comment]
Make sure you specify it with a trailing comma: `(0xab,)`

**Comment by jumpkick** [comment]
I was able to do one byte on the blind that's in range... the other one doesn't respond to anything (gives 204 sometimes but doesn't do anything, so probably need a better bluetooth dongle)

**Comment by dnschneid** [comment]
Alright. I've updated the code to only need one byte, removed the broken pcap search method, and instead made blind search and keyscanning part of the main library.

I added `examples/search.py` to automate the finding and scanning of blinds.

There's enough hooks now that one could make the two other examples (httpserver and HomeAssistant) auto-detect and populate blinds if nothing is specified, although that would be a slow start-up time (could be a minute or more per blind).

Let me know if the new stuff works for you.

**Comment by jumpkick** [comment]
nice!

Here's what I did to run it on my RetroPi to test (think the RPi has the better antenna than my HA box)...

```
sudo hcitool lescan # Make sure we can see some SmartBlind_DFU so we know BLE is working from this host
	
# extra steps to get running on my RetroPi
cd /tmp
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py

# Install deps, clone and set-up	
sudo pip3 install pygatt pexpect
git clone https://github.com/dnschneid/pysmartblinds
cd pysmartblinds/examples
ln -s ../pysmartblinds/pysmartblinds.py
	
# Run the search
sudo ./search.py
```

It did succeed in finding 1 key, the first 2 scans failed somewhere in the 3x range... 
```
Scanning for 10 seconds...
Found C2:XXXXX, D7:XXXXX, C4:XXXXX, DE:XXXXX, DA:XXXXX
[C2:XXXXX]: keyscan failed
[D7:XXXXX]: keyscan failed
[C4:XXXXX]: b1
C4:XXXXX = b1
[DE:XXXXX]: keyscan failed
[DA:XXXXX]: 07^CTraceback (most recent call last):
```

So being that 3 of my blinds are on other floors and up to 25 feet away, I'm guessing that 3 retries is not going to be enough to get through brute forcing 256 combos...  so I bumped up the retries to 300 in keyscan() and I'm rerunning. 😄

**Comment by jumpkick** [comment]
Just upping the tries doesn't work... 
```
Scanning for 10 seconds...
Found C4: XXXXX, DE: XXXXX, D7:XXXXX, C2:XXXXX
[C4:XXXXX]: b1
C4:XXXXX = b1
[DE:XXXXX]: 30
```
We know from packet inspection that de:XXXXX should be "12",  we passed right by that value...  😢

**Comment by jumpkick** [comment]
Final for that run was 3/4:

```
Scanning for 10 seconds...
Found C4:XXXXX, DE:XXXXX, D7:XXXXX, C2:XXXXX
[C4:XXXXX]: b1
C4:XXXXX = b1
[DE:XXXXX]: keyscan failed
[D7:XXXXX]: cd
D7:XXXXX = cd
[C2:6XXXXX]: 58
C2:XXXXX = 58
```

**Comment by jumpkick** [comment]
Hmm...  I couldn't really relocate the Pi easily, but I did do another run... 

All 5 blinds couged up their their keys this time and then I was able to control all 5 from the httpserver example!

It may have been that my PS3 that was running the first couple of runs (which uses BT for it's controller) was interfering with the Pi a bit.   The 2 of the blinds that failed in the first run were also very close to the Pi, so I'm not sure range would be the culprit.   I guess BTLE can be a bit tricky. 

It might be worth logging an error message with the retries, and mentioning that one should try to reposition closer or remove other Bluetooth devices nearby/in the path.

Next thing I'll try again from my Intel machine and if I can do alright there, I'll seeing if I can move the blind component into my hass.io docker container

**Comment by dnschneid** [comment]
Thanks for the thorough testing!  5 sounds like as good a number as any.

I haven't really looked at the right way to distribute the HASS component; to be honest, right now I just scatter symlinks until things work.

**Comment by jumpkick** [comment]
I tried this on the hassio IDE shell...   (it mounts the same /share and /config volumes as hass but has git installed):
```
mkdir -p /share/source
cd /share/source
git clone https://github.com/dnschneid/pysmartblinds.git

mkdir -p /config/custom_components/cover /config/deps/lib/python-3.6/site-packages
cd /share/source/pysmartblinds
cp examples/mysmartblinds.py /config/custom_components/cover
cp -r pysmartblinds /config/deps/lib/python-3.6/site-packages
```

First the server choked on _**SERVICE_TO_METHOD**_ import, so I removed that and restarted...

Unfortunately, hass seems to ignore the deps folder during startup and I get 
```
14:  File "/config/custom_components/cover/mysmartblinds.py", line 31, in <module>
15:    from pysmartblinds import Blind
16:ModuleNotFoundError: No module named 'pysmartblinds'
```
I logged into the container and checked /deps and the file is there @ /config/deps/lib/python3.6/site-packages/pysmartblinds/pysmartblinds.py 

I also tried /config/deps/lib/python3.6/pysmartblinds/pysmartblinds.py

I'm guessing to the HA component go, I need to fork the repo, write a setup.py for pypi and then set the hassio "Custom deps deployment" plugin to "git+https://github.com/jumpkick/pysmartblinds.git"

Where do you have your symlinks for pysmartblinds.py?

**Comment by dnschneid** [comment]
I think I have a symlink in custom_components/cover pointing to mysmartblinds.py, and then a symlink in the same directory as the real mysmartblinds.py pointing to pysmartblinds.py.

It's not pretty; we can discuss better packaging in a separate issue.  Going to close this one because I think the original issue is solved.
