### ISSUE TITLE
SERVICE_TO_METHOD removed in HA 0.77

### ISSUE THREAD

**Issue by deftdawg** [dnschneid/pysmartblinds#7]
mysmartblinds.py fails to init in HA in versions >= 0.77

The SERVICE_TO_METHOD symbol was removed with this commit:
https://github.com/home-assistant/home-assistant/commit/b682e48e12686eec8776ab5eb527c1e36a5826e3#diff-aec3f5346a76b74ad2bee24c7f56f886L76

Lines [24](https://github.com/dnschneid/pysmartblinds/blob/master/examples/mysmartblinds.py#L24), [54](https://github.com/dnschneid/pysmartblinds/blob/master/examples/mysmartblinds.py#L54) and [55](https://github.com/dnschneid/pysmartblinds/blob/master/examples/mysmartblinds.py#L55) of examples/mysmartblinds.py reference that symbol.

If I knew what to change it to I'd submit a patch... 

This was tested by dropping mysmartblinds.py into /config/custom_components/cover/ and pysmartblinds.py into /config/deps/lib/python3.6/site-packages/ on HASS.IO 0.82.1

**Comment by dnschneid** [comment]
We need to find a way to modify COVER_SERVICE_SCHEMA.  Maybe the right thing to do is just propose a patch to HomeAssistant to add to the schema instead of hacking it in at run-time.

**Comment by dnschneid** [comment]
Of course, once we move to get a component merged into HomeAssistant, we can make it dependent on adding to the schema...but getting this ready to be merged in will take longer.

**Comment by dnschneid** [comment]
For now there's a homeassistant patch file that can be applied to enable the transition option; I'll look into upstreaming this in the future.
